name: Rebuild and deploy data files

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fontTools youseedee
    - name: Fetch youseedee database
      run: python -m youseedee 0x20
    - name: Fetch Noto fonts
      uses: actions/checkout@v2
      with:
        repository: googlefonts/noto-fonts
        path: noto-fonts
    - name: Fetch Noto CJK
      uses: actions/checkout@v2
      with:
        repository: googlefonts/noto-cjk
        path: noto-cjk
    - name: Fetch Noto Emoji
      uses: actions/checkout@v2
      with:
        repository: googlefonts/noto-emoji
        path: noto-emoji
    - name: Gather data
      run: python gather-codepoint-data.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: blocks/*.json blocks.json fontfiles.json
